//
//  ChildInteractor.swift
//  DataPassingInCleanSwift
//
//  Created by Aqeel Ahmed on 02/02/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChildBusinessLogic
{
  func doSomething(request: Child.Something.Request)
}

protocol ChildDataStore
{
  //var name: String { get set }
}

class ChildInteractor: ChildBusinessLogic, ChildDataStore
{
  var presenter: ChildPresentationLogic?
  var worker: ChildWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Child.Something.Request)
  {
    worker = ChildWorker()
    worker?.doSomeWork()
    
    let response = Child.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
