//
//  ChildModels.swift
//  DataPassingInCleanSwift
//
//  Created by Aqeel Ahmed on 02/02/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Child
{
    // MARK: Get Entered Text
    enum GetEnteredText
    {
        struct Request
        {
            
        }
        struct Response
        {
            var enteredText: String
        }
        struct ViewModel
        {
            var enteredText: String
        }
    }
}
