//
//  ChildInteractor.swift
//  DataPassingInCleanSwift
//
//  Created by Aqeel Ahmed on 02/02/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChildBusinessLogic
{
    func getEnteredText(request: Child.GetEnteredText.Request)
}

protocol ChildDataStore
{
    var enteredText: String { get set }
}

class ChildInteractor: ChildBusinessLogic, ChildDataStore
{
    var presenter: ChildPresentationLogic?
    var worker: ChildWorker?
    var enteredText: String = ""
    
    // MARK: Do something
    
    func getEnteredText(request: Child.GetEnteredText.Request)
    {
        
        let response = Child.GetEnteredText.Response(enteredText: self.enteredText)
        presenter?.presentEnteredText(response: response)
    }
}
