//
//  ParentPresenter.swift
//  DataPassingInCleanSwift
//
//  Created by Aqeel Ahmed on 02/02/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ParentPresentationLogic
{
  func presentSomething(response: Parent.Something.Response)
}

class ParentPresenter: ParentPresentationLogic
{
  weak var viewController: ParentDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Parent.Something.Response)
  {
    let viewModel = Parent.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
