//
//  ParentInteractor.swift
//  DataPassingInCleanSwift
//
//  Created by Aqeel Ahmed on 02/02/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ParentBusinessLogic
{
  func doSomething(request: Parent.Something.Request)
}

protocol ParentDataStore
{
  //var name: String { get set }
}

class ParentInteractor: ParentBusinessLogic, ParentDataStore
{
  var presenter: ParentPresentationLogic?
  var worker: ParentWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Parent.Something.Request)
  {
    worker = ParentWorker()
    worker?.doSomeWork()
    
    let response = Parent.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
