//
//  ParentInteractor.swift
//  DataPassingInCleanSwift
//
//  Created by Aqeel Ahmed on 02/02/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ParentBusinessLogic
{
    func setEnteredText(request: Parent.SetEnteredText.Request)
}

protocol ParentDataStore
{
    var enteredText: String { get set }
}

class ParentInteractor: ParentBusinessLogic, ParentDataStore
{
    var presenter: ParentPresentationLogic?
    var worker: ParentWorker?
    var enteredText: String = ""
    
    // MARK: Do something
    
    func setEnteredText(request: Parent.SetEnteredText.Request)
    {
        self.enteredText = request.enteredText
        
        let response = Parent.SetEnteredText.Response()
        presenter?.presentChild(response: response)
    }
}
